# -*- coding: utf-8 -*-
"""Module1_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fM1IoDNcKc8mzKy8nRGkYp6Xo03xAlWx
"""

#Propts the user to enter two numbers (integers arguments: num1 and num2) and adds the total of numbers in the range of two arguments
def total():
  running = True
  numbers = 0

  while running:
    num1 = int(input('Enter the first number:'))
    
    num2 = int(input('Enter the second numer:'))

    for i in range(num1, num2):
      numbers = sum(range(num1, num2))+num2
    else:
      running = False
    print('The total of the numbers in between is', numbers)


total()

total()

total()

total()